### 3d20 dice roll success table

This code can be used to create an array that contains probabilities of success when rolling 3 20-sided die and comparing the results against 2 different values, a skill value and a difficulty class. It can be a useful reference for a tabletop game depending on its rules.

The skill value represents a character's aptitude for the check, from 1 to 20. 
The difficulty class represents the extent of the dice challenge, from 2 to 20.

The code isn't optimized at all, since it only needs to run once to give the results. It outputs a 2D array that contains probabilities of success for each possible instance of skill and difficulty.

In [412]:
import numpy as np

## Define the problem
sizeof_die = 20
nof_dice = 3
outcomes = sizeof_die ** nof_dice

## Define and initialize the dimensions of a sample space
sample_space = np.zeros(shape=(outcomes, nof_dice), dtype=int)

## For cleaner output
float_formatter = "{:.4f}".format
np.set_printoptions(formatter={'float_kind':float_formatter})

In [413]:
## assign proper dice values to the sample space
for x in range (0, 20):
    for y in range (0, 20):
        for z in range (0, 20):
            sample_space[400*x + 20*y + z] = [x+1, y+1, z+1]

In [414]:
print(sample_space)

[[ 1  1  1]
 [ 1  1  2]
 [ 1  1  3]
 ...
 [20 20 18]
 [20 20 19]
 [20 20 20]]


In [415]:
## Checks the successfulness of a dice roll, given 
## a sample, the skill rank and the difficulty class.
## Currently works with 3d20 rolls only
def check_success(sample, skill, dc):
    
    ## Store dice rolls for comparison
    A = sample[0]
    B = sample[1]
    C = sample[2]
    ## Calculate roll distance from skill value
    a = np.abs(np.subtract(A, skill))
    b = np.abs(np.subtract(B, skill))
    c = np.abs(np.subtract(C, skill))
    
    ## Select the dice value closest to the skill value, 
    ## or the highest dice value in case of a tie
    if a < b:
        t = a
        T = A
    elif a > b:
        t = b
        T = B
    else: 
        if A > B:
            t = a
            T = A
        else:
            t = b
            T = B
        
    if c < t:
        result = C
    elif c > t:
        result = T
    else:
        if C > T:
            result = C
        else:
            result = T
    
    ## Check to see if the resultant dice value meets or exceeds the required difficulty
    if result >= dc:
        return 1 ## success
    else:
        return 0 ## failure

In [416]:
## Calculates the probability of success, given 
## the sample space, skill level and roll difficulty class
def check_probability(sample_space, skill, dc):
    count = 0
    checks = len(sample_space)
    for x in range(0, checks):
        count += check_success(sample_space[x], skill, dc)
        
    return count / checks

In [417]:
print(check_probability(sample_space, 10, 2))

0.999125


In [428]:
success_table = np.zeros(shape=(sizeof_die, sizeof_die - 1), dtype=float)

for x in range (0, sizeof_die):
    for y in range (0, sizeof_die - 1):
        success_table[x, y] = check_probability(sample_space, x+1, y+2)

In [429]:
## Presto!
print(success_table)

[[0.8574 0.7290 0.6141 0.5120 0.4219 0.3430 0.2746 0.2160 0.1664 0.1250
  0.0911 0.0640 0.0429 0.0270 0.0156 0.0080 0.0034 0.0010 0.0001]
 [0.8851 0.7425 0.6141 0.5120 0.4219 0.3430 0.2746 0.2160 0.1664 0.1250
  0.0911 0.0640 0.0429 0.0270 0.0156 0.0080 0.0034 0.0010 0.0001]
 [0.9099 0.7950 0.6524 0.5240 0.4219 0.3430 0.2746 0.2160 0.1664 0.1250
  0.0911 0.0640 0.0429 0.0270 0.0156 0.0080 0.0034 0.0010 0.0001]
 [0.9316 0.8415 0.7266 0.5840 0.4556 0.3535 0.2746 0.2160 0.1664 0.1250
  0.0911 0.0640 0.0429 0.0270 0.0156 0.0080 0.0034 0.0010 0.0001]
 [0.9504 0.8820 0.7919 0.6770 0.5344 0.4060 0.3039 0.2250 0.1664 0.1250
  0.0911 0.0640 0.0429 0.0270 0.0156 0.0080 0.0034 0.0010 0.0001]
 [0.9661 0.9165 0.8481 0.7580 0.6431 0.5005 0.3721 0.2700 0.1911 0.1325
  0.0911 0.0640 0.0429 0.0270 0.0156 0.0080 0.0034 0.0010 0.0001]
 [0.9789 0.9450 0.8954 0.8270 0.7369 0.6220 0.4794 0.3510 0.2489 0.1700
  0.1114 0.0700 0.0429 0.0270 0.0156 0.0080 0.0034 0.0010 0.0001]
 [0.9886 0.9675 0.9336 0.8840 0.81